api:
    dashboard: true

providers:
    docker:
        endpoint: "unix:///var/run/docker.sock"
        exposedByDefault: false

    # Dynamic configuration for TLS
    file:
        filename: /etc/traefik/dynamic/config.yml
        watch: true

entryPoints:
    web:
        address: :80
        http:
            redirections:
                entryPoint:
                    to: websecure
                    scheme: https

    websecure:
        address: :443

log:
    level: DEBUG

serversTransport:
    insecureSkipVerify: true
    rootCAs:
        - /etc/traefik/ssl/minica.pem
