# FOR DEVELOPMENT PURPOSES ONLY!
# Server infrastructure has been moved to a separate project

version: "3.8"

services:
    traefik:
        image: traefik:v2.9
        container_name: quizae-traefik
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./development-environment/traefik:/etc/traefik:ro
        networks:
            - quizae_traefik
        labels:
            - traefik.enable=true
            - traefik.http.routers.traefik.entrypoints=websecure
            - traefik.http.routers.traefik.rule=Host(`traefik.quizae.wtf`)
            - traefik.http.routers.traefik.tls=true
            - traefik.http.routers.traefik.service=api@internal

    mysql:
        image: mysql:8.0.32
        container_name: quizae-mysql
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - quizae_db_access
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: quizae
        ports:
            - "33061:3306"

    backend:
        build:
            context: ./
            dockerfile: Dockerfile
            target: development
        container_name: quizae-backend
        depends_on:
            - mysql
        volumes:
            - ./:/usr/src/app:rw
        networks:
            - quizae_db_access
            - quizae_traefik
        labels:
            - traefik.enable=true
            - traefik.http.routers.backend.entrypoints=websecure
            - traefik.http.routers.backend.rule=Host(`api.quizae.wtf`)
            - traefik.http.routers.backend.tls=true
        environment:
            APP_ENV: dev
            DATABASE_URL: mysql://root:root@quizae-mysql:3306/quizae
            JWT_SECRET: 3493ab26a038b1c70a8273e75ebbc9e7

networks:
    quizae_traefik:
        external: true
    quizae_db_access:
        external: true

volumes:
    mysql_data:
