version: "3.8"

services:
    traefik:
        image: traefik:v2.9
        ports:
            - 80:80
            - 443:443
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./development-environment/traefik:/etc/traefik:ro
        networks:
            - traefik
        labels:
            - traefik.enable=true
            - traefik.docker.network=quizae_traefik
            - traefik.http.routers.traefik.entrypoints=websecure
            - traefik.http.routers.traefik.rule=Host(`traefik.quizae.wtf`)
            - traefik.http.routers.traefik.tls=true
            - traefik.http.routers.traefik.service=api@internal

    mongodb:
        image: mongo:6.0.4
        container_name: quizae-mongodb
        volumes:
            - mongo_data:/data/db
        networks:
            - dbaccess
        restart: on-failure
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
            MONGO_INITDB_DATABASE: quizae

    backend:
        depends_on:
            - mongodb
        build:
            context: ./
            dockerfile: Dockerfile
            target: development
        volumes:
            - ./:/usr/src/app:rw
        networks:
            - traefik
        labels:
            - traefik.enable=true
            - traefik.docker.network=quizae_traefik
            - traefik.http.routers.backend.entrypoints=websecure
            - traefik.http.routers.backend.rule=Host(`api.quizae.wtf`)
            - traefik.http.routers.backend.tls=true
        restart: on-failure

    mongodb-express:
        image: mongo-express:latest
        depends_on:
            - mongodb
        networks:
            - dbaccess
            - traefik
        restart: on-failure
        environment:
            ME_CONFIG_MONGODB_SERVER: quizae-mongodb
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: root
        labels:
            - traefik.enable=true
            - traefik.docker.network=quizae_traefik
            - traefik.http.routers.mongodb-express.entrypoints=websecure
            - traefik.http.routers.mongodb-express.rule=Host(`mongodb-express.quizae.wtf`)
            - traefik.http.routers.mongodb-express.tls=true

networks:
    traefik:
        name: quizae_traefik
    dbaccess:
        name: quizae_db_access

volumes:
    mongo_data:
