# FOR DEVELOPMENT PURPOSES ONLY!
# Server infrastructure has been moved to a separate project

version: "3.8"

services:
    traefik:
        image: traefik:v2.9
        container_name: quizae-traefik
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./development-environment/traefik:/etc/traefik:ro
        networks:
            - quizae_traefik
        labels:
            - traefik.enable=true
            - traefik.http.routers.traefik.entrypoints=websecure
            - traefik.http.routers.traefik.rule=Host(`traefik.quizae.wtf`)
            - traefik.http.routers.traefik.tls=true
            - traefik.http.routers.traefik.service=api@internal

    mongodb:
        image: mongo:6.0.4
        container_name: quizae-mongodb
        restart: unless-stopped
        entrypoint: [
            "/usr/bin/mongod",
            "--keyFile",
            "/data/file.key",
            "--replSet",
            "rs0",
            "--journal",
            "--bind_ip_all"
        ]
        volumes:
            - mongo_data:/data/db
            - ./development-environment/mongo/file.key:/data/file.key
            - ./development-environment/mongo/change-replica.sh:/tmp/change-replica.sh
        networks:
            - quizae_db_access
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
            MONGO_INITDB_DATABASE: quizae

    backend:
        build:
            context: ./
            dockerfile: Dockerfile
            target: development
        container_name: quizae-backend
        restart: unless-stopped
        depends_on:
            - mongodb
        volumes:
            - ./:/usr/src/app:rw
        networks:
            - quizae_db_access
            - quizae_traefik
        labels:
            - traefik.enable=true
            - traefik.http.routers.backend.entrypoints=websecure
            - traefik.http.routers.backend.rule=Host(`api.quizae.wtf`)
            - traefik.http.routers.backend.tls=true
        environment:
            APP_ENV: dev
            DATABASE_URL: mongodb://root:root@quizae-mongodb/quizae?authSource=admin&replicaSet=rs0
            JWT_SECRET: 3493ab26a038b1c70a8273e75ebbc9e7

    mongodb-express:
        image: mongo-express:latest
        container_name: quizae-mongodb-express
        restart: unless-stopped
        depends_on:
            - mongodb
        networks:
            - quizae_db_access
            - quizae_traefik
        environment:
            ME_CONFIG_MONGODB_SERVER: quizae-mongodb
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: root
        labels:
            - traefik.enable=true
            - traefik.http.routers.mongodb-express.entrypoints=websecure
            - traefik.http.routers.mongodb-express.rule=Host(`mongodb-express.quizae.wtf`)
            - traefik.http.routers.mongodb-express.tls=true

networks:
    quizae_traefik:
        external: true
    quizae_db_access:
        external: true

volumes:
    mongo_data:
