api:
    dashboard: true

providers:
    docker:
        endpoint: "unix:///var/run/docker.sock"
        exposedByDefault: false

    # Dynamic configuration
    file:
        filename: /etc/traefik/dynamic.yaml
        watch: true

entryPoints:
    web:
        address: :80
        http:
            redirections:
                entryPoint:
                    to: websecure
                    scheme: https

    websecure:
        address: :443

certificatesResolvers:
    defaultResolver:
        acme:
            email: hey@martinmicka.me
            storage: acme.json
            tlsChallenge: {}
