name: Build and Test

on:
    push:
        branches:
            - main

jobs:
    install:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Branch
              uses: actions/checkout@v3

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 19
                  cache: npm

            - name: Start MongoDB
              uses: supercharge/mongodb-github-action@1.8.0
              with:
                  mongodb-version: 6.0
                  mongodb-username: root
                  mongodb-password: password
                  mongodb-replica-set: quizae-test

            - name: Install Dependencies
              run: npm ci

            - name: Generate DB Types
              run: npx prisma generate

            - name: Run Tests
              run: npm run test
              env:
                  CI: true
                  APP_ENV: test
                  DATABASE_URL: mongodb://root:password@127.0.0.1:27017/?retryWrites=true&w=majority
                  JWT_SECRET: 3493ab26a038b1c70a8273e75ebbc9e7

            - name: Run Integration Tests
              run: npm run test:e2e
              env:
                  CI: true
                  APP_ENV: test
                  DATABASE_URL: mongodb://root:password@127.0.0.1:27017/?retryWrites=true&w=majority
                  JWT_SECRET: 3493ab26a038b1c70a8273e75ebbc9e7
