name: Prepare Image and Push Release

on:
    release:
        types:
            - published

jobs:
    echo-release-tag:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Context
                uses: actions/checkout@v3

            -   name: Generate Docker Meta
                id: docker-meta
                uses: docker/metadata-action@v4
                with:
                    images: ghcr.io/Mareddie/quizae
                    tags: |
                        type=semver,pattern={{version}}

            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v2

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2

            -   name: Login to GitHub Container Registry
                uses: docker/login-action@v2
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Build and Push Docker Image
                uses: docker/build-push-action@v4
                with:
                    context: .
                    target: production
                    push: true
                    tags: ${{ steps.docker-meta.outputs.tags }}
                    labels: ${{ steps.docker-meta.outputs.labels }}
