name: Run Tests

on:
# Updates to main are locked - therefore, we don't need to run this pipeline on push to main.
#    push:
#        branches:
#            - main

    pull_request:
        branches:
            - main

env:
    CI: true
    APP_ENV: test
    DATABASE_URL: mysql://root:root@127.0.0.1:3306/quizae
    JWT_SECRET: 3493ab26a038b1c70a8273e75ebbc9e7

jobs:
    install-and-test:
        name: Install Project and Run Tests
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Branch
                uses: actions/checkout@v3

            -   name: Use Node.js
                uses: actions/setup-node@v3
                with:
                    node-version: 19
                    cache: npm

            -   name: Init MySQL
                uses: shogo82148/actions-setup-mysql@v1
                with:
                    mysql-version: '8.0'
                    root-password: 'root'

            -   name: Create Testing Database
                run: mysql -uroot -proot -h127.0.0.1 -e 'CREATE DATABASE quizae'

            -   name: Install Dependencies
                run: npm ci

            -   name: Generate Types, Update DB
                run: npx prisma db push

            -   name: Run Tests
                run: npm run test

            -   name: Run Integration Tests
                run: npm run test:e2e
